### ISSUE TITLE
fix op:OATH/WETH pool liquidity

### ISSUE THREAD

**Issue by mendesfabio** [balancer/dune-spellbook#47]
## Context 

[Beethoven](https://op.beets.fi/pool/0xd20f6f1d8a675cdca155cb07b5dc9042c467153f0002000000000000000000bc) says TVL is $870k but on Dune it is $13M.

**Comment by viniabussafi** [comment]
Been working on an improvement for the liquidity spell on this [query](https://dune.com/queries/3240145).
Basically, we are exposed to outliers in pricing information that comes from `prices.usd `and `dex.prices`. This tends to happen with tokens with less volume of trades.
Therefore, I have created a [whitelist](https://dune.com/queries/3240078) for tokens considered as pricing assets (e.g. WETH, USDC, DAI, USDT and a few others). The idea is to have the pool liquidity for weighted pools calculated, whenever possible, based on the balance and price of these pricing assets. This logic can be found on the `pool_liquidity_estimates` and `pool_liquidity_estimates_2 `CTEs and accounts for the following cases:

- Pool with only one pricing asset,
- Pool with more than one pricing asset
- Pool with no pricing asset

From my initial analysis, this would have a marginal impact on most chains, with the only exception being optimism, due to the case mentioned in this issue.
I will follow-up on this task by running a PR on the spellbook and checking its impact on our liquidity data.
This PR will be combined with https://github.com/balancer/dune-spellbook/issues/44

**Comment by viniabussafi** [comment]
Reference for token whitelist file on the balancer namespace on spellbook: https://github.com/duneanalytics/spellbook/blob/main/models/oneinch/oneinch_contract_addresses.sql

Will mention distortion on OATH price on my PR and then reference it on dune discord

**Comment by viniabussafi** [comment]
[PR](https://github.com/duneanalytics/spellbook/pull/4960) created, waiting for review.

**Comment by viniabussafi** [comment]
PR merged and issue fixed
