### ISSUE TITLE
fix different data types on spells

### ISSUE THREAD

**Issue by mendesfabio** [balancer/dune-spellbook#55]
I worked with our Spells recently and types inconsistency bothered me - e.g. `pool_address` is `varchar` in one spell, but `varbinary` in the other one. I'm going to list what I found below for us to think of better way to handle it.

**Comment by viniabussafi** [comment]
Listing some of the inconsistencies/potential improvements I found:

- token_{}_amount_raw:
decimal on balancer.trades
uint256 on balancer_v2.trades

- contract_address
varchar on bpt_prices
varbinary on dex.prices and prices.usd

General thoughts on the columns of our spells:
- Pool address can be named as contract_address, pool_address and pool (balances spell). We should establish a standard.
- We should add a timestamp column on the liquidity spells, because this conversion is repeated across all our TVL visuals, to properly format the x-axis

**Comment by viniabussafi** [comment]
> - contract_address
> varchar on bpt_prices
> varbinary on dex.prices and prices.usd

Fixed - now it's varbinary across all spells

> - Should add decimals to the bpt prices spell

Added

**Comment by viniabussafi** [comment]
fixed - spells are consistent now. We can do another round of these improvements with v3
